### ISSUE TITLE
Fluency logger should support same fields as FluentLogger

### ISSUE THREAD

**Issue by jklap** [sndyuk/logback-more-appenders#17]
Currently the FluentLogger appender pushes logging data into multiple fluentd fields such as "message", "caller",  "marker", "throwable", MDC properties and custom fields. The new fluency logger only supports a single field "msg" which makes it impossible to swap out FluentLogger with Fluency.

**Comment by takumakanari** [comment]
Hi @jklap, I made a patch like the following:

https://github.com/takumakanari/logback-more-appenders/blob/add-more-fields/src/main/java/ch/qos/logback/more/appenders/FluencyLogbackAppender.java#L61

Does it solve your issue?

**Comment by anthofo** [comment]
Same thing for me, I would need the same fields for switching

**Comment by takumakanari** [comment]
@anthofo If the following patch solves your issue, I'll make p-r to include it.

It adds * caller*/* marker*/* throwable*/*MDC*/*additionals* and *log(==message)*.

https://github.com/takumakanari/logback-more-appenders/blob/add-more-fields/src/main/java/ch/qos/logback/more/appenders/FluencyLogbackAppender.java#L61

**Comment by anthofo** [comment]
@takumakanari I tried it and it works :) But the fields are not exactly the same : 
- "msg" instead of "message"
- And the log level, I get an object {"levelInt": 20000,"levelStr": "INFO"} instead of just a String "INFO"

**Comment by takumakanari** [comment]
@anthofo Thanks for your message.

> "msg" instead of "message"

yes, because 'msg' has used for other field already so I named new field 'log'. could I ask is it difficult to replace field 'message' to 'log' in your Fluentd configuration?

**Comment by anthofo** [comment]
The name is ok for me, but would not be the same between the different appenders, which can be confusing

**Comment by takumakanari** [comment]
I see, I've changed its name to *message*.
Also 2nd part about log level, I've fixed it to dump level string instead of object.

**Comment by anthofo** [comment]
Sounds nice to me :)

**Comment by takumakanari** [comment]
Thank you! I'll submit a patch after a little bit testing.

**Comment by sndyuk** [comment]
I released the version 1.4.2

**Comment by jklap** [comment]
Thank you @takumakanari and @sndyuk!

**Comment by jklap** [comment]
Was testing this today and in looking back at the code it seems we still have the "msg" field there. I like the idea of being able to use a layout to customize the message but do we really need "msg" and "message"? I'd think we should have something like this:

if (layout != null) {
            msg = layout.doLayout(rawData);
} else {
           msg = rawData.getFormattedMessage();
}
data.put("message", msg);


And then drop the "msg" field.
